<?xml version="1.0" encoding="ASCII"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="fsmTrace" nsURI="fsmTrace" nsPrefix="fsmTrace">
  <eClassifiers xsi:type="ecore:EClass" name="SpecificTrace">
    <eStructuralFeatures xsi:type="ecore:EReference" name="Fsm_AssignValueAction_Execute_Sequence" upperBound="-1" eType="//Steps/Fsm_AssignValueAction_Execute"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="Fsm_DecreaseValueAction_Execute_Sequence" upperBound="-1" eType="//Steps/Fsm_DecreaseValueAction_Execute"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="Fsm_EqualNumberGuard_Holds_Sequence" upperBound="-1" eType="//Steps/Fsm_EqualNumberGuard_Holds"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="Fsm_GreaterThanNumberGuard_Holds_Sequence" upperBound="-1" eType="//Steps/Fsm_GreaterThanNumberGuard_Holds"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="Fsm_Guard_Holds_Sequence" upperBound="-1" eType="//Steps/Fsm_Guard_Holds"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="Fsm_IncreaseValueAction_Execute_Sequence" upperBound="-1" eType="//Steps/Fsm_IncreaseValueAction_Execute"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="Fsm_LessThanNumberGuard_Holds_Sequence" upperBound="-1" eType="//Steps/Fsm_LessThanNumberGuard_Holds"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="Fsm_NumberGuard_Holds_Sequence" upperBound="-1" eType="//Steps/Fsm_NumberGuard_Holds"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="Fsm_StateMachine_AssignInitialValues_Sequence" upperBound="-1" eType="//Steps/Fsm_StateMachine_AssignInitialValues"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="Fsm_StateMachine_Step_Sequence" upperBound="-1" eType="//Steps/Fsm_StateMachine_Step"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="Fsm_Transition_Fire_Sequence" upperBound="-1" eType="//Steps/Fsm_Transition_Fire"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="statesTrace" upperBound="-1" eType="//States/State" containment="true"/>
    <eGenericSuperTypes>
      <eTypeArguments>
        <eTypeArguments eClassifier="//Steps/SpecificStep"/>
        <eClassifier xsi:type="ecore:EClass" href="../../../plugin/fr.inria.diverse.trace.commons.model/model/GenericTrace.ecore#//SequentialStep"/>
      </eTypeArguments>
      <eClassifier xsi:type="ecore:EClass" href="../../../plugin/fr.inria.diverse.trace.commons.model/model/GenericTrace.ecore#//Trace"/>
    </eGenericSuperTypes>
  </eClassifiers>
  <eSubpackages name="Steps" nsURI="fsmTrace_Steps" nsPrefix="events">
    <eClassifiers xsi:type="ecore:EClass" name="Fsm_AssignValueAction_Execute">
      <eSuperTypes href="#//Steps/Fsm_Transition_Fire_AbstractSubStep"/>
      <eSuperTypes href="#//Steps/SpecificStep"/>
      <eSuperTypes href="../../../plugin/fr.inria.diverse.trace.commons.model/model/GenericTrace.ecore#//SmallStep"/>
      <eOperations name="getCaller" lowerBound="1">
        <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
          <details key="body" value="return (org.gemoc.sample.legacyfsm.xsfsm.xsfsm.fsm.AssignValueAction) this.getMseoccurrence().getMse().getCaller();"/>
        </eAnnotations>
        <eType xsi:type="ecore:EClass" href="../../org.gemoc.sample.legacyfsm.xsfsm.xsfsm/model/XSFSM.ecore#//AssignValueAction"/>
      </eOperations>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="Fsm_DecreaseValueAction_Execute">
      <eSuperTypes href="#//Steps/Fsm_Transition_Fire_AbstractSubStep"/>
      <eSuperTypes href="#//Steps/SpecificStep"/>
      <eSuperTypes href="../../../plugin/fr.inria.diverse.trace.commons.model/model/GenericTrace.ecore#//SmallStep"/>
      <eOperations name="getCaller" lowerBound="1">
        <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
          <details key="body" value="return (org.gemoc.sample.legacyfsm.xsfsm.xsfsm.fsm.DecreaseValueAction) this.getMseoccurrence().getMse().getCaller();"/>
        </eAnnotations>
        <eType xsi:type="ecore:EClass" href="../../org.gemoc.sample.legacyfsm.xsfsm.xsfsm/model/XSFSM.ecore#//DecreaseValueAction"/>
      </eOperations>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="Fsm_EqualNumberGuard_Holds">
      <eSuperTypes href="#//Steps/Fsm_StateMachine_Step_AbstractSubStep"/>
      <eSuperTypes href="#//Steps/SpecificStep"/>
      <eSuperTypes href="../../../plugin/fr.inria.diverse.trace.commons.model/model/GenericTrace.ecore#//SmallStep"/>
      <eOperations name="getCaller" lowerBound="1">
        <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
          <details key="body" value="return (org.gemoc.sample.legacyfsm.xsfsm.xsfsm.fsm.EqualNumberGuard) this.getMseoccurrence().getMse().getCaller();"/>
        </eAnnotations>
        <eType xsi:type="ecore:EClass" href="../../org.gemoc.sample.legacyfsm.xsfsm.xsfsm/model/XSFSM.ecore#//EqualNumberGuard"/>
      </eOperations>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="Fsm_GreaterThanNumberGuard_Holds">
      <eSuperTypes href="#//Steps/Fsm_StateMachine_Step_AbstractSubStep"/>
      <eSuperTypes href="#//Steps/SpecificStep"/>
      <eSuperTypes href="../../../plugin/fr.inria.diverse.trace.commons.model/model/GenericTrace.ecore#//SmallStep"/>
      <eOperations name="getCaller" lowerBound="1">
        <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
          <details key="body" value="return (org.gemoc.sample.legacyfsm.xsfsm.xsfsm.fsm.GreaterThanNumberGuard) this.getMseoccurrence().getMse().getCaller();"/>
        </eAnnotations>
        <eType xsi:type="ecore:EClass" href="../../org.gemoc.sample.legacyfsm.xsfsm.xsfsm/model/XSFSM.ecore#//GreaterThanNumberGuard"/>
      </eOperations>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="Fsm_Guard_Holds">
      <eSuperTypes href="#//Steps/Fsm_StateMachine_Step_AbstractSubStep"/>
      <eSuperTypes href="#//Steps/SpecificStep"/>
      <eSuperTypes href="../../../plugin/fr.inria.diverse.trace.commons.model/model/GenericTrace.ecore#//SmallStep"/>
      <eOperations name="getCaller" lowerBound="1">
        <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
          <details key="body" value="return (org.gemoc.sample.legacyfsm.xsfsm.xsfsm.fsm.Guard) this.getMseoccurrence().getMse().getCaller();"/>
        </eAnnotations>
        <eType xsi:type="ecore:EClass" href="../../org.gemoc.sample.legacyfsm.xsfsm.xsfsm/model/XSFSM.ecore#//Guard"/>
      </eOperations>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="Fsm_IncreaseValueAction_Execute">
      <eSuperTypes href="#//Steps/Fsm_Transition_Fire_AbstractSubStep"/>
      <eSuperTypes href="#//Steps/SpecificStep"/>
      <eSuperTypes href="../../../plugin/fr.inria.diverse.trace.commons.model/model/GenericTrace.ecore#//SmallStep"/>
      <eOperations name="getCaller" lowerBound="1">
        <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
          <details key="body" value="return (org.gemoc.sample.legacyfsm.xsfsm.xsfsm.fsm.IncreaseValueAction) this.getMseoccurrence().getMse().getCaller();"/>
        </eAnnotations>
        <eType xsi:type="ecore:EClass" href="../../org.gemoc.sample.legacyfsm.xsfsm.xsfsm/model/XSFSM.ecore#//IncreaseValueAction"/>
      </eOperations>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="Fsm_LessThanNumberGuard_Holds">
      <eSuperTypes href="#//Steps/Fsm_StateMachine_Step_AbstractSubStep"/>
      <eSuperTypes href="#//Steps/SpecificStep"/>
      <eSuperTypes href="../../../plugin/fr.inria.diverse.trace.commons.model/model/GenericTrace.ecore#//SmallStep"/>
      <eOperations name="getCaller" lowerBound="1">
        <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
          <details key="body" value="return (org.gemoc.sample.legacyfsm.xsfsm.xsfsm.fsm.LessThanNumberGuard) this.getMseoccurrence().getMse().getCaller();"/>
        </eAnnotations>
        <eType xsi:type="ecore:EClass" href="../../org.gemoc.sample.legacyfsm.xsfsm.xsfsm/model/XSFSM.ecore#//LessThanNumberGuard"/>
      </eOperations>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="Fsm_NumberGuard_Holds">
      <eSuperTypes href="#//Steps/Fsm_StateMachine_Step_AbstractSubStep"/>
      <eSuperTypes href="#//Steps/SpecificStep"/>
      <eSuperTypes href="../../../plugin/fr.inria.diverse.trace.commons.model/model/GenericTrace.ecore#//SmallStep"/>
      <eOperations name="getCaller" lowerBound="1">
        <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
          <details key="body" value="return (org.gemoc.sample.legacyfsm.xsfsm.xsfsm.fsm.NumberGuard) this.getMseoccurrence().getMse().getCaller();"/>
        </eAnnotations>
        <eType xsi:type="ecore:EClass" href="../../org.gemoc.sample.legacyfsm.xsfsm.xsfsm/model/XSFSM.ecore#//NumberGuard"/>
      </eOperations>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="Fsm_StateMachine_AssignInitialValues">
      <eSuperTypes href="#//Steps/SpecificStep"/>
      <eSuperTypes href="../../../plugin/fr.inria.diverse.trace.commons.model/model/GenericTrace.ecore#//SmallStep"/>
      <eOperations name="getCaller" lowerBound="1">
        <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
          <details key="body" value="return (org.gemoc.sample.legacyfsm.xsfsm.xsfsm.fsm.StateMachine) this.getMseoccurrence().getMse().getCaller();"/>
        </eAnnotations>
        <eType xsi:type="ecore:EClass" href="../../org.gemoc.sample.legacyfsm.xsfsm.xsfsm/model/XSFSM.ecore#//StateMachine"/>
      </eOperations>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="Fsm_StateMachine_Step">
      <eOperations name="getCaller" lowerBound="1">
        <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
          <details key="body" value="return (org.gemoc.sample.legacyfsm.xsfsm.xsfsm.fsm.StateMachine) this.getMseoccurrence().getMse().getCaller();"/>
        </eAnnotations>
        <eType xsi:type="ecore:EClass" href="../../org.gemoc.sample.legacyfsm.xsfsm.xsfsm/model/XSFSM.ecore#//StateMachine"/>
      </eOperations>
      <eGenericSuperTypes eClassifier="//Steps/SpecificStep"/>
      <eGenericSuperTypes>
        <eTypeArguments eClassifier="//Steps/Fsm_StateMachine_Step_AbstractSubStep"/>
        <eClassifier xsi:type="ecore:EClass" href="../../../plugin/fr.inria.diverse.trace.commons.model/model/GenericTrace.ecore#//SequentialStep"/>
      </eGenericSuperTypes>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="Fsm_StateMachine_Step_AbstractSubStep" abstract="true" interface="true" eSuperTypes="//Steps/SpecificStep"/>
    <eClassifiers xsi:type="ecore:EClass" name="Fsm_StateMachine_Step_ImplicitStep">
      <eSuperTypes href="#//Steps/Fsm_StateMachine_Step_AbstractSubStep"/>
      <eSuperTypes href="../../../plugin/fr.inria.diverse.trace.commons.model/model/GenericTrace.ecore#//SmallStep"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="Fsm_Transition_Fire">
      <eOperations name="getCaller" lowerBound="1">
        <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
          <details key="body" value="return (org.gemoc.sample.legacyfsm.xsfsm.xsfsm.fsm.Transition) this.getMseoccurrence().getMse().getCaller();"/>
        </eAnnotations>
        <eType xsi:type="ecore:EClass" href="../../org.gemoc.sample.legacyfsm.xsfsm.xsfsm/model/XSFSM.ecore#//Transition"/>
      </eOperations>
      <eGenericSuperTypes eClassifier="//Steps/Fsm_StateMachine_Step_AbstractSubStep"/>
      <eGenericSuperTypes eClassifier="//Steps/SpecificStep"/>
      <eGenericSuperTypes>
        <eTypeArguments eClassifier="//Steps/Fsm_Transition_Fire_AbstractSubStep"/>
        <eClassifier xsi:type="ecore:EClass" href="../../../plugin/fr.inria.diverse.trace.commons.model/model/GenericTrace.ecore#//SequentialStep"/>
      </eGenericSuperTypes>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="Fsm_Transition_Fire_AbstractSubStep" abstract="true" interface="true" eSuperTypes="//Steps/SpecificStep"/>
    <eClassifiers xsi:type="ecore:EClass" name="Fsm_Transition_Fire_ImplicitStep">
      <eSuperTypes href="#//Steps/Fsm_Transition_Fire_AbstractSubStep"/>
      <eSuperTypes href="../../../plugin/fr.inria.diverse.trace.commons.model/model/GenericTrace.ecore#//SmallStep"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="RootImplicitStep">
      <eSuperTypes href="../../../plugin/fr.inria.diverse.trace.commons.model/model/GenericTrace.ecore#//SmallStep"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="SpecificStep" abstract="true" interface="true">
      <eSuperTypes href="../../../plugin/fr.inria.diverse.trace.commons.model/model/GenericTrace.ecore#//Step"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="endingState" eType="//States/State" eOpposite="//States/State/endedSteps"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="startingState" lowerBound="1" eType="//States/State" eOpposite="//States/State/startedSteps"/>
    </eClassifiers>
  </eSubpackages>
  <eSubpackages name="States" nsURI="fsmTrace_States" nsPrefix="tracedclasses">
    <eClassifiers xsi:type="ecore:EClass" name="State">
      <eStructuralFeatures xsi:type="ecore:EReference" name="endedSteps" upperBound="-1" eType="//Steps/SpecificStep" eOpposite="//Steps/SpecificStep/endingState"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="startedSteps" upperBound="-1" eType="//Steps/SpecificStep" eOpposite="//Steps/SpecificStep/startingState"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="Value" abstract="true" interface="true">
      <eStructuralFeatures xsi:type="ecore:EReference" name="statesNoOpposite" lowerBound="1" upperBound="-1" eType="//States/State" changeable="false" volatile="true" transient="true" derived="true"/>
    </eClassifiers>
  </eSubpackages>
</ecore:EPackage>
